config/routes.rb
Rails.application.routes.draw do
  root 'terms#new'

  resources :terms

  resources :justifications

  resources :artworks

end

app/models/artwork.rb
# == Schema Information
#
# Table name: artworks
#
#  id                    :integer          not null, primary key
#  image                 :string(255)
#  register_number       :string(255)
#  name                  :string(255)
#  material              :string(255)
#  dimensions            :string(255)
#  state_of_conservation :string(255)
#  observation           :string(255)
#  term_id               :integer
#  created_at            :datetime
#  updated_at            :datetime
#

class Artwork < ActiveRecord::Base
	belongs_to :term

	mount_uploader :image, ImageUploader
end

app/models/justification.rb
# == Schema Information
#
# Table name: justifications
#
#  id         :integer          not null, primary key
#  text       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Justification < ActiveRecord::Base
	has_many :justification_terms, dependent: :destroy
	has_many :terms, through: :justification_terms
end

app/models/justification_term.rb
# == Schema Information
#
# Table name: justification_terms
#
#  id               :integer          not null, primary key
#  justification_id :integer
#  term_id          :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class JustificationTerm < ActiveRecord::Base
  belongs_to :justification
  belongs_to :term
end

app/models/term.rb
# == Schema Information
#
# Table name: terms
#
#  id                        :integer          not null, primary key
#  legal_representer         :string(255)
#  cpf_cnpj                  :string(255)
#  address                   :string(255)
#  contact                   :string(255)
#  role                      :string(255)
#  start_of_period           :string(255)
#  end_of_period             :string(255)
#  justification_description :string(255)
#  removing_way              :string(255)
#  returning_way             :string(255)
#  number_of_items           :string(255)
#  created_at                :datetime
#  updated_at                :datetime
#

class Term < ActiveRecord::Base
	has_many :artworks, dependent: :destroy
	has_many :justification_terms, dependent: :destroy
	has_many :justifications, through: :justification_terms

	accepts_nested_attributes_for :artworks, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :justifications, reject_if: :all_blank, allow_destroy: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  private

	def layout_by_resource
		if devise_controller?
			"public"
		else
			# "application"
			"public"
		end
	end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @artworks = Artwork.all
    respond_with(@artworks)
  end

  def show
    respond_with(@artwork)
  end

  def new
    @artwork = Artwork.new
    respond_with(@artwork)
  end

  def edit
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.save
    respond_with(@artwork)
  end

  def update
    @artwork.update(artwork_params)
    respond_with(@artwork)
  end

  def destroy
    @artwork.destroy
    respond_with(@artwork)
  end

  private
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    def artwork_params
      params.require(:artwork).permit(:image, :register_number, :name, :material, :dimensions, :state_of_conservation, :observation, :term_id)
    end
end

app/controllers/justifications_controller.rb
class JustificationsController < ApplicationController
  before_action :set_justification, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @justifications = Justification.all
    respond_with(@justifications)
  end

  def show
    respond_with(@justification)
  end

  def new
    @justification = Justification.new
    respond_with(@justification)
  end

  def edit
  end

  def create
    @justification = Justification.new(justification_params)
    @justification.save
    respond_with(@justification)
  end

  def update
    @justification.update(justification_params)
    respond_with(@justification)
  end

  def destroy
    @justification.destroy
    respond_with(@justification)
  end

  private
    def set_justification
      @justification = Justification.find(params[:id])
    end

    def justification_params
      params.require(:justification).permit(:text)
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @terms = Term.all
    respond_with(@terms)
  end

  def show
    @justifications = Justification.all
    respond_to do |format|
      format.html do 
        render locals: {
          show_as_pdf: false,
        }
      end
      format.pdf do
        @filename = "Termo.pdf"
        # @pdf = render_to_string :pdf => "file",
        render :pdf => "file",
          :file => "terms/show.html.erb",
          :layout => "layouts/application.pdf.erb",
          :show_as_html => params[:debug].present?,
          :encoding => 'utf-8',
          # :javascript_delay => 1000,
          :margin => {
            :top      => 0,
            :bottom   => 0,
            :left     => 0,
            :right    => 0
          },
          locals: {
            show_as_pdf: true,
          }
        # send_data(@pdf, filename: @filename, type: "application/pdf")
      end
    end
  end

  def new
    @term = Term.new
    @justifications = Justification.all
    respond_with(@term)
  end

  def edit
  end

  def create
    @term = Term.new(term_params)
    @term.save
    @justifications = Justification.all

    # respond_to do |format|
    #   format.html do 
    #     render locals: {
    #       show_as_pdf: false,
    #     }
    #   end
    #   format.pdf do
        @filename = "Termo.pdf"
        # @pdf = render_to_string :pdf => "file",
        render :pdf => "file",
          :file => "terms/show.html.erb",
          :layout => "layouts/application.pdf.erb",
          :show_as_html => params[:debug].present?,
          :encoding => 'utf-8',
          # :javascript_delay => 1000,
          :margin => {
            :top      => 5,
            :bottom   => 5,
            :left     => 5,
            :right    => 5
          },
          locals: {
            show_as_pdf: true,
          }
        # send_data(@pdf, filename: @filename, type: "application/pdf")
    #   end
    # end

    # respond_with(@term)
  end

  def update
    @term.update(term_params)
    respond_with(@term)
  end

  def destroy
    @term.destroy
    respond_with(@term)
  end

  private
  
  def set_term
    @term = Term.find(params[:id])
  end

  def term_params
    params.require(:term).permit(:legal_representer, :cpf_cnpj, :address, :contact, :role, :start_of_period, :end_of_period, :justification_description, :removing_way, :returning_way, :number_of_items, artworks_attributes: [:id, :image, :register_number, :name, :material, :dimensions, :state_of_conservation, :observation], justification_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/justifications_helper.rb
module JustificationsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/artworks/_form.html.erb
<%= form_for(@artwork, html: { class: 'form-horizontal' }) do |f| %>
  <% if @artwork.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :image, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :register_number, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :register_number, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :material, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :material, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :dimensions, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :dimensions, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state_of_conservation, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :state_of_conservation, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :observation, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :observation, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :term_id, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :term_id, class: 'form-control' %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <%= link_to( t('Back'), artworks_path, class: 'btn btn-white' ) %>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12 col-md-10">
        <h2>Artworks</h2>
        <ol class="breadcrumb">
            <li><%= link_to t('Artworks'), artworks_path %></li>
            <li class="active"><strong><%= t('Edit') %></strong></li>
        </ol>
    </div>
    <div class="col-sm-12 col-md-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><%= t('Edit') %> artwork <%= @artwork.name %><small></small></h5>
                <div class="ibox-tools">
                    <div class="pull-right">
                        <%= link_to '<i class="fa fa-reply"></i>'.html_safe, artworks_path %>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <%= render "form" %>
            </div>
        </div>
    </div>
</div>

app/views/artworks/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12 col-md-10">
        <h2>Artworks</h2>
        <ol class="breadcrumb">
            <li class="active"><strong><%= t('Artworks') %></strong></li>
        </ol>
    </div>
    <div class="col-sm-12 col-md-2 m-t-lg">
        <%= link_to t('Create'), new_artwork_path, class: 'btn btn-lg btn-w-m btn-primary btn-outline pull-right' %>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><%= t('List') %> artworks<small></small></h5>
            </div>
            <div class="ibox-content">
                <table id="artwork-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th rowspan="2">Image</th>
                            <th rowspan="2">Register number</th>
                            <th rowspan="2">Name</th>
                            <th rowspan="2">Material</th>
                            <th rowspan="2">Dimensions</th>
                            <th rowspan="2">State of conservation</th>
                            <th rowspan="2">Observation</th>
                            <th rowspan="2">Term</th>
                            <th class="text-center" colspan="3"><%= t('Actions') %></th>
                        </tr>
                        <tr>
                            <th class="text-center" width="70"><%= t('Show') %></th>
                            <th class="text-center" width="70"><%= t('Edit') %></th>
                            <th class="text-center" width="70"><%= t('Delete') %></th>
                        </tr>
                    </thead>
                <tbody>
                <% @artworks.each do |artwork| %>
                    <tr>
                        <td><%= artwork.image %></td>
                        <td><%= artwork.register_number %></td>
                        <td><%= artwork.name %></td>
                        <td><%= artwork.material %></td>
                        <td><%= artwork.dimensions %></td>
                        <td><%= artwork.state_of_conservation %></td>
                        <td><%= artwork.observation %></td>
                        <td><%= artwork.term %></td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-eye"></i>'.html_safe, artwork, class: 'btn btn-info btn-outline btn-sm'%>
                        </td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_artwork_path(artwork), class: 'btn btn-success btn-outline btn-sm' %>
                        </td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, artwork, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-outline btn-sm' %>
                        </td>
                    </tr>
                <% end %>
                </table>
            </div>
        </div>
    </div>
</div>
<% content_for :javascript do %>
<script>
$(document).ready(function() {
    $('#artwork-table').dataTable({
        responsive: true,
        "columnDefs": [ 
            { 
                "targets": [8, 9, 10], 
                "orderable": false 
            } 
        ],
    });
});
</script>
<% end %>

app/views/artworks/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12 col-md-10">
        <h2>Artworks</h2>
        <ol class="breadcrumb">
            <li><%= link_to t('Artworks'), artworks_path %></li>
            <li class="active"><strong><%= t('Create') %></strong></li>
        </ol>
    </div>
    <div class="col-sm-12 col-md-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><%= t('Create') %> artwork<small></small></h5>
                <div class="ibox-tools">
                    <div class="pull-right">
                        <%= link_to '<i class="fa fa-reply"></i>'.html_safe, artworks_path %>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <%= render "form" %>
            </div>
        </div>
    </div>
</div>

app/views/artworks/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12 col-md-10">
    <h2>Artworks</h2>
    <ol class="breadcrumb">
      <li><%= link_to t('Artworks'), artworks_path %></li>
      <li class="active"><strong><%= t('Edit') %></strong></li>
    </ol>
  </div>
  <div class="col-sm-12 col-md-2">

  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><%= t('View') %> artwork <%= @artwork.name %><small></small></h5>
        <div class="ibox-tools">
          <div class="pull-right">
            <%= link_to '<i class="fa fa-reply"></i>'.html_safe, artworks_path %>
          </div>
        </div>
      </div>
      <div class="ibox-content">
        <div class="row">
          <label class="control-label col-sm-2">Image</label>
          <div class="col-sm-10">
            <%= @artwork.image %>
          </div>
        </div>
        <div class="row">
          <label class="control-label col-sm-2">Register number</label>
          <div class="col-sm-10">
            <%= @artwork.register_number %>
          </div>
        </div>
        <div class="row">
          <label class="control-label col-sm-2">Name</label>
          <div class="col-sm-10">
            <%= @artwork.name %>
          </div>
        </div>
        <div class="row">
          <label class="control-label col-sm-2">Material</label>
          <div class="col-sm-10">
            <%= @artwork.material %>
          </div>
        </div>
        <div class="row">
          <label class="control-label col-sm-2">Dimensions</label>
          <div class="col-sm-10">
            <%= @artwork.dimensions %>
          </div>
        </div>
        <div class="row">
          <label class="control-label col-sm-2">State of conservation</label>
          <div class="col-sm-10">
            <%= @artwork.state_of_conservation %>
          </div>
        </div>
        <div class="row">
          <label class="control-label col-sm-2">Observation</label>
          <div class="col-sm-10">
            <%= @artwork.observation %>
          </div>
        </div>
        <div class="row">
          <label class="control-label col-sm-2">Term</label>
          <div class="col-sm-10">
            <%= @artwork.term %>
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="row clearfix">
          <div class="col-sm-10 col-sm-offset-2">
            <%= link_to( t('Back'), artworks_path, class: 'btn btn-white' ) %>
            <%= link_to t('Edit'), edit_artwork_path(@artwork), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/justifications/_form.html.erb
<%= form_for(@justification, html: { class: 'form-horizontal' }) do |f| %>
  <% if @justification.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
      <h2><%= pluralize(@justification.errors.count, "error") %> prohibited this justification from being saved:</h2>

      <ul>
      <% @justification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :text, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :text, class: 'form-control' %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <%= link_to( t('Back'), justifications_path, class: 'btn btn-white' ) %>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/justifications/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12 col-md-10">
        <h2>Justifications</h2>
        <ol class="breadcrumb">
            <li><%= link_to t('Justifications'), justifications_path %></li>
            <li class="active"><strong><%= t('Edit') %></strong></li>
        </ol>
    </div>
    <div class="col-sm-12 col-md-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><%= t('Edit') %> justification <%= @justification.id %><small></small></h5>
                <div class="ibox-tools">
                    <div class="pull-right">
                        <%= link_to '<i class="fa fa-reply"></i>'.html_safe, justifications_path %>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <%= render "form" %>
            </div>
        </div>
    </div>
</div>

app/views/justifications/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12 col-md-10">
        <h2>Justifications</h2>
        <ol class="breadcrumb">
            <li class="active"><strong><%= t('Justifications') %></strong></li>
        </ol>
    </div>
    <div class="col-sm-12 col-md-2 m-t-lg">
        <%= link_to t('Create'), new_justification_path, class: 'btn btn-lg btn-w-m btn-primary btn-outline pull-right' %>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><%= t('List') %> justifications<small></small></h5>
            </div>
            <div class="ibox-content">
                <table id="justification-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th rowspan="2">Text</th>
                            <th class="text-center" colspan="3"><%= t('Actions') %></th>
                        </tr>
                        <tr>
                            <th class="text-center" width="70"><%= t('Show') %></th>
                            <th class="text-center" width="70"><%= t('Edit') %></th>
                            <th class="text-center" width="70"><%= t('Delete') %></th>
                        </tr>
                    </thead>
                <tbody>
                <% @justifications.each do |justification| %>
                    <tr>
                        <td><%= justification.text %></td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-eye"></i>'.html_safe, justification, class: 'btn btn-info btn-outline btn-sm'%>
                        </td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_justification_path(justification), class: 'btn btn-success btn-outline btn-sm' %>
                        </td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, justification, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-outline btn-sm' %>
                        </td>
                    </tr>
                <% end %>
                </table>
            </div>
        </div>
    </div>
</div>
<% content_for :javascript do %>
<script>
$(document).ready(function() {
    $('#justification-table').dataTable({
        responsive: true,
        "columnDefs": [ 
            { 
                "targets": [1, 2, 3], 
                "orderable": false 
            } 
        ],
    });
});
</script>
<% end %>

app/views/justifications/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12 col-md-10">
        <h2>Justifications</h2>
        <ol class="breadcrumb">
            <li><%= link_to t('Justifications'), justifications_path %></li>
            <li class="active"><strong><%= t('Create') %></strong></li>
        </ol>
    </div>
    <div class="col-sm-12 col-md-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><%= t('Create') %> justification<small></small></h5>
                <div class="ibox-tools">
                    <div class="pull-right">
                        <%= link_to '<i class="fa fa-reply"></i>'.html_safe, justifications_path %>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <%= render "form" %>
            </div>
        </div>
    </div>
</div>

app/views/justifications/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12 col-md-10">
    <h2>Justifications</h2>
    <ol class="breadcrumb">
      <li><%= link_to t('Justifications'), justifications_path %></li>
      <li class="active"><strong><%= t('Edit') %></strong></li>
    </ol>
  </div>
  <div class="col-sm-12 col-md-2">

  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><%= t('View') %> justification <%= @justification.id %><small></small></h5>
        <div class="ibox-tools">
          <div class="pull-right">
            <%= link_to '<i class="fa fa-reply"></i>'.html_safe, justifications_path %>
          </div>
        </div>
      </div>
      <div class="ibox-content">
                <div class="row">
          <label class="control-label col-sm-2">Text</label>
          <div class="col-sm-10">
          <%= @justification.text %>
          </div>
        </div>
                <div class="hr-line-dashed"></div>
        <div class="row clearfix">
          <div class="col-sm-10 col-sm-offset-2">
            <%= link_to( t('Back'), justifications_path, class: 'btn btn-white' ) %>
            <%= link_to t('Edit'), edit_justification_path(@justification), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014-2015
    </div>
</div>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="/">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search" />
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="#">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>

app/views/terms/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12 col-md-10">
        <h2>Terms</h2>
        <ol class="breadcrumb">
            <li><%= link_to t('Terms'), terms_path %></li>
            <li class="active"><strong><%= t('Edit') %></strong></li>
        </ol>
    </div>
    <div class="col-sm-12 col-md-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><%= t('Edit') %> term <%= @term.id %><small></small></h5>
                <div class="ibox-tools">
                    <div class="pull-right">
                        <%= link_to '<i class="fa fa-reply"></i>'.html_safe, terms_path %>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <%= render "form" %>
            </div>
        </div>
    </div>
</div>

app/views/terms/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12 col-md-10">
        <h2>Terms</h2>
        <ol class="breadcrumb">
            <li class="active"><strong><%= t('Terms') %></strong></li>
        </ol>
    </div>
    <div class="col-sm-12 col-md-2 m-t-lg">
        <%= link_to t('Create'), new_term_path, class: 'btn btn-lg btn-w-m btn-primary btn-outline pull-right' %>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><%= t('List') %> terms<small></small></h5>
            </div>
            <div class="ibox-content">
                <table id="term-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th rowspan="2">Legal representer</th>
                            <th rowspan="2">Cpf cnpj</th>
                            <th rowspan="2">Address</th>
                            <th rowspan="2">Contact</th>
                            <th rowspan="2">Role</th>
                            <th rowspan="2">Start of period</th>
                            <th rowspan="2">End of period</th>
                            <th rowspan="2">Justification description</th>
                            <th rowspan="2">Removing way</th>
                            <th rowspan="2">Returning way</th>
                            <th rowspan="2">Number of items</th>
                            <th class="text-center" colspan="3"><%= t('Actions') %></th>
                        </tr>
                        <tr>
                            <th class="text-center" width="70"><%= t('Show') %></th>
                            <th class="text-center" width="70"><%= t('Edit') %></th>
                            <th class="text-center" width="70"><%= t('Delete') %></th>
                        </tr>
                    </thead>
                <tbody>
                <% @terms.each do |term| %>
                    <tr>
                        <td><%= term.legal_representer %></td>
                        <td><%= term.cpf_cnpj %></td>
                        <td><%= term.address %></td>
                        <td><%= term.contact %></td>
                        <td><%= term.role %></td>
                        <td><%= term.start_of_period %></td>
                        <td><%= term.end_of_period %></td>
                        <td><%= term.justification_description %></td>
                        <td><%= term.removing_way %></td>
                        <td><%= term.returning_way %></td>
                        <td><%= term.number_of_items %></td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-eye"></i>'.html_safe, term, class: 'btn btn-info btn-outline btn-sm'%>
                        </td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_term_path(term), class: 'btn btn-success btn-outline btn-sm' %>
                        </td>
                        <td class="text-center">
                            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, term, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-outline btn-sm' %>
                        </td>
                    </tr>
                <% end %>
                </table>
            </div>
        </div>
    </div>
</div>
<% content_for :javascript do %>
<script>
$(document).ready(function() {
    $('#term-table').dataTable({
        responsive: true,
        "columnDefs": [ 
            { 
                "targets": [11, 12, 13], 
                "orderable": false 
            } 
        ],
    });
});
</script>
<% end %>